### ISSUE TITLE
Wallet won't start on ubuntu 18.04

### ISSUE THREAD

**Issue by oliverlj** [sumoproject/SumoGUIWallet#2]
Hello,

I got this error => 
oliver@oliver-rig-lyon-2:~/crypto/Sumokoin_GUI_Wallet-v0.0.5-Linux-x64$ ./wallet 
Traceback (most recent call last):
  File "wallet.py", line 8, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "main.py", line 17, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "app/hub.py", line 41, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "webui/__init__.py", line 23, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 687, in load_module
ImportError: /usr/lib/x86_64-linux-gnu/libgstaudio-1.0.so.0: undefined symbol: gst_aggregator_finish_buffer
[11269] Failed to execute script wallet

**Comment by ghost** [comment]
Try with the latest 0.0.6 wallet, solved it for me

**Comment by sumoproject** [comment]
Solved - closed

**Comment by quangvu3** [comment]
Yes, v0.0.6 works on Ubuntu 18.04, one problem is the system tray icon doesn't show. This can be solved by installing `sni-qt`:

```
sudo apt install sni-qt
```
